from typing import Protocol, List, Optional
from uuid import UUID
from app.domain.entities.job import Job
from app.domain.entities.skill import Skill
from app.domain.entities.resume import Resume

class JobRepository(Protocol):
    """Interface for Job persistence."""
    async def save(self, job: Job) -> Job: ...
    async def get_by_id(self, job_id: UUID) -> Optional[Job]: ...
    async def list_jobs(self, limit: int = 10, offset: int = 0) -> List[Job]: ...
    async def get_by_url(self, url: str) -> Optional[Job]: ...

class SkillRepository(Protocol):
    """Interface for Skill taxonomy persistence."""
    async def get_by_name(self, name: str) -> Optional[Skill]: ...
    async def save(self, skill: Skill) -> Skill: ...
    async def list_all(self) -> List[Skill]: ...

class ResumeRepository(Protocol):
    """Interface for Resume persistence."""
    async def save(self, resume: Resume) -> Resume: ...
    async def get_by_id(self, resume_id: UUID) -> Optional[Resume]: ...
    async def get_by_user_id(self, user_id: UUID) -> List[Resume]: ...
